[window]
padding = {x = 0, y = 0}
opacity = 0.6
title = "hemanth@kali"

[font]
normal = {family = "JetBrains Mono"}
size = 10

[font.bold]
family = "JetBrains Mono"
style = "regular"

[font.bold_italic]
family = "JetBrains Mono"
style = "Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"


[colors]
[colors.primary]
background = "#000000"
foreground = "#dfdfdf"

[colors.normal]
black =   '#000000'
red =     '#ad4900'
green =   '#6981ff'
yellow =  '#af8005'
blue =    '#76a600'
magenta = '#6981ff'
cyan =    '#76a600'
white =   '#deeed1'

[colors.bright]
black =   '#5E5C64'
red =     '#AD4900'
green =   '#33D17A'
yellow =  '#B28817'
blue =    '#2CA600'
magenta = '#990B6C'
cyan =    '#33C7DE'
white =   '#03FC89'

[colors.dim]
black =   '#232323'
red =     '#74423f'
green =   '#5e6547'
yellow =  '#8b7653'
blue =    '#556b79'
magenta = '#6e4962'
cyan =    '#5c8482'
white =   '#828282'

[cursor]
style = "Underline"
blink_interval = 750

vi_mode_style = "Underline"

[keyboard]
bindings = [
    { key = "T", mods = "Control|Shift", action = "CreateNewTab" },
]

[env]
TERM = "xterm-256color"
LIBGL_ALWAYS_SOFTWARE = "1"
